ALTER TABLE users COMMENT = '业务用户表';
ALTER TABLE users MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE users MODIFY COLUMN user_no VARCHAR(64) NOT NULL COMMENT '业务用户编号';
ALTER TABLE users MODIFY COLUMN nickname VARCHAR(128) NOT NULL COMMENT '用户昵称';
ALTER TABLE users MODIFY COLUMN level_name VARCHAR(64) NOT NULL COMMENT '会员等级名称';
ALTER TABLE users MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE orders COMMENT = '订单主表';
ALTER TABLE orders MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE orders MODIFY COLUMN order_no VARCHAR(64) NOT NULL COMMENT '业务订单号';
ALTER TABLE orders MODIFY COLUMN user_no VARCHAR(64) NOT NULL COMMENT '业务用户编号';
ALTER TABLE orders MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '订单状态';
ALTER TABLE orders MODIFY COLUMN amount DECIMAL(12, 2) NOT NULL COMMENT '订单金额';
ALTER TABLE orders MODIFY COLUMN paid_at TIMESTAMP NULL COMMENT '支付成功时间';
ALTER TABLE orders MODIFY COLUMN completed_at TIMESTAMP NULL COMMENT '订单完成时间';
ALTER TABLE orders MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE payments COMMENT = '支付记录表';
ALTER TABLE payments MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE payments MODIFY COLUMN order_no VARCHAR(64) NOT NULL COMMENT '业务订单号';
ALTER TABLE payments MODIFY COLUMN channel VARCHAR(32) NOT NULL COMMENT '支付渠道';
ALTER TABLE payments MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '支付状态';
ALTER TABLE payments MODIFY COLUMN callback_status VARCHAR(32) NOT NULL COMMENT '支付回调状态';
ALTER TABLE payments MODIFY COLUMN paid_at TIMESTAMP NULL COMMENT '支付成功时间';
ALTER TABLE payments MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE refunds COMMENT = '退款记录表';
ALTER TABLE refunds MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE refunds MODIFY COLUMN order_no VARCHAR(64) NOT NULL COMMENT '业务订单号';
ALTER TABLE refunds MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '退款状态';
ALTER TABLE refunds MODIFY COLUMN reason VARCHAR(255) NULL COMMENT '退款原因或拒绝原因';
ALTER TABLE refunds MODIFY COLUMN requested_at TIMESTAMP NULL COMMENT '退款申请时间';
ALTER TABLE refunds MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE benefits COMMENT = '会员权益发放记录表';
ALTER TABLE benefits MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE benefits MODIFY COLUMN user_no VARCHAR(64) NOT NULL COMMENT '业务用户编号';
ALTER TABLE benefits MODIFY COLUMN order_no VARCHAR(64) NOT NULL COMMENT '业务订单号';
ALTER TABLE benefits MODIFY COLUMN benefit_name VARCHAR(128) NOT NULL COMMENT '权益名称';
ALTER TABLE benefits MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '权益发放状态';
ALTER TABLE benefits MODIFY COLUMN fail_reason VARCHAR(255) NULL COMMENT '权益发放失败原因';
ALTER TABLE benefits MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE agent_sessions COMMENT = 'Agent 问答会话记录表';
ALTER TABLE agent_sessions MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE agent_sessions MODIFY COLUMN trace_id VARCHAR(64) NOT NULL COMMENT '链路追踪ID';
ALTER TABLE agent_sessions MODIFY COLUMN question TEXT NOT NULL COMMENT '用户或客服提问内容';
ALTER TABLE agent_sessions MODIFY COLUMN answer TEXT NULL COMMENT 'Agent 回答内容';
ALTER TABLE agent_sessions MODIFY COLUMN duration_ms BIGINT NOT NULL DEFAULT 0 COMMENT '本次问答耗时毫秒数';
ALTER TABLE agent_sessions MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE agent_tool_logs COMMENT = 'Agent 工具调用日志表';
ALTER TABLE agent_tool_logs MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE agent_tool_logs MODIFY COLUMN trace_id VARCHAR(64) NOT NULL COMMENT '链路追踪ID';
ALTER TABLE agent_tool_logs MODIFY COLUMN tool_name VARCHAR(128) NOT NULL COMMENT '工具名称';
ALTER TABLE agent_tool_logs MODIFY COLUMN input_json TEXT NOT NULL COMMENT '工具入参 JSON';
ALTER TABLE agent_tool_logs MODIFY COLUMN output_summary TEXT NULL COMMENT '工具出参摘要';
ALTER TABLE agent_tool_logs MODIFY COLUMN duration_ms BIGINT NOT NULL COMMENT '工具调用耗时毫秒数';
ALTER TABLE agent_tool_logs MODIFY COLUMN success TINYINT(1) NOT NULL COMMENT '是否调用成功，1成功，0失败';
ALTER TABLE agent_tool_logs MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE rag_hit_logs COMMENT = 'RAG 知识命中日志表';
ALTER TABLE rag_hit_logs MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE rag_hit_logs MODIFY COLUMN trace_id VARCHAR(64) NOT NULL COMMENT '链路追踪ID';
ALTER TABLE rag_hit_logs MODIFY COLUMN source VARCHAR(255) NOT NULL COMMENT '命中的知识来源文件';
ALTER TABLE rag_hit_logs MODIFY COLUMN score DECIMAL(12, 8) NOT NULL COMMENT '向量检索相似度得分';
ALTER TABLE rag_hit_logs MODIFY COLUMN content_preview VARCHAR(512) NOT NULL COMMENT '命中文本摘要';
ALTER TABLE rag_hit_logs MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
